# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df = pd.read_csv('Data_Scrap_Tokopedia.csv',  on_bad_lines='skip')
print(df)

df[df.duplicated(keep=False)]
df2 = df.drop_duplicates()
df2[df2.duplicated(keep=False)]

df.columns

df2['Nama Toko'] = df2['Nama Toko'].str.replace(r"[\"\'\|\?\=\.\<\>\@\#\*\_\-\!\&\,\(\)\^\ ]",'')

df2['Lokasi'] = df2['Lokasi'].str.replace(r"[\"\'\|\?\=\.\<\>\@\#\*\_\-\!\&\,\(\)\^\ ]",'')

df2['Nama Toko']

x = df2.iloc[:, [0,1,3,4]].values

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 2:])
x[:, 2:] = imputer.transform(x[:, 2:])

x_train, x_test= train_test_split(x, test_size=0.2, random_state=1)

sc = StandardScaler()
x_train[:,2:] = sc.fit_transform(x_train[:,2:])
x_test[:,2:] = sc.fit_transform(x_test[:,2:])

x_train

x_test

z = pd.DataFrame(x_train)

x2 = z.iloc[:,[0,2,3]].values

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(
    sparse=True, handle_unknown='ignore'), [10])], remainder='passthrough')
x2 = np.array(ct.fit_transform(x2))

f = pd.DataFrame(x2)

f
